# Generated by Django 3.2.10 on 2023-10-16 07:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('warriors_app', '0011_alter_goodsimage_goods'),
    ]

    operations = [
        migrations.AddField(
            model_name='warrior',
            name='new_race',
            field=models.CharField(blank=True, choices=[('s', 'student'), ('d', 'developer'), ('t', 'teamlead')], max_length=1, null=True, verbose_name='Новая Расса'),
        ),
    ]
